version: "3.7"

services:
  master:     # Master Node
    image: hadoop-master-image
    build:
      context: .
      dockerfile: # Ваш код
    ports:
      # Ваш код     # Namenode
      # Ваш код     # Resource Manager
      - "19888:19888"   # History Server
    container_name: master
    volumes: 
      - ./app:/home/bigdata/app     # jar files
      - ./data:/home/bigdata/data   # data to copy to HDFS
    networks:
      - hd-network

  worker:     # Worker Node
    image: hadoop-worker-image
    build:
      context: .
      dockerfile: # Ваш код
    networks:
      - hd-network

networks:
  hd-network: # Network
    driver: # Ваш код
    ipam:
      config:
      # Ваш код